name: Development workflow

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    name: Build
    env:
      SCHEME: "FooManagement-Dev"
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
    runs-on: macOS-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
#     - name: Install CocoaPods
#       run: |
#         gem install cocoapods
#         pod install
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.2.app
    - name: Xcode build
      run: |
        cd Swift
        xcodebuild clean build -scheme MyApp -destination 'platform=iOS Simulator,name=iPhone 12,OS=16.4.1'
    - name: Upload products
      uses: actions/upload-artifact@v2
      with:
        name: Products
        path: DerivedData/Build/Products

  unit_test:
    name: Unit test
    env:
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
      UNIT_TEST_TARGET: "FooManagementTests"
    runs-on: macOS-latest
    needs: build
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
#     - name: Install CocoaPods
#       run: |
#         gem install cocoapods
#         pod install
    - name: Install SPM dependencies
      run: swift package update
    - name: Download products
      uses: actions/download-artifact@v1
      with:
        name: Products
    - name: Run unit tests
      run: |
        set -o pipefail && xcodebuild test-without-building -xctestrun $(find . -type f -name "*.xctestrun") -destination "platform=iOS Simulator,name=$DEVICE" -derivedDataPath $DERIVED_DATA_PATH -enableCodeCoverage YES -only-testing:$UNIT_TEST_TARGET | xcpretty --color --simple
    - name: Upload test logs
      uses: actions/upload-artifact@v1
      with:
        name: TestLogs
        path: DerivedData/Logs/Test

  ui_test:
    name: UI test
    env:
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
      UI_TEST_TARGET: "FooManagementUITests"
    runs-on: macOS-latest
    needs: build
    steps:
    - name: Checkout project 
      uses: actions/checkout@v2
#     - name: Install CocoaPods
#       run: |
#         gem install cocoapods
#         pod install
    - name: Install SPM dependencies
      run: swift package update
    - name: Download products
      uses: actions/download-artifact@v1
      with:
        name: Products
    - name: Run UI tests
      run: |
        set -o pipefail && xcodebuild test-without-building -xctestrun $(find . -type f -name "*.xctestrun") -destination "platform=iOS Simulator,name=$DEVICE" -derivedDataPath $DERIVED_DATA_PATH -enableCodeCoverage YES -only-testing:$UI_TEST_TARGET | xcpretty  --color --simple
